### ISSUE TITLE
Reduce compute time overhead with parallel processing

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Omniscape.jl#10]
Send tasks in batches instead of one at a time?

Overhead per solve is non-trivial (maybe on the order of milliseconds?). With tens or hundreds of thousands of solves, it adds up.

@ranjanan any thoughts on this? I know dividing the number of tasks by the number of workers/threads is not necessarily ideal because then there may be idle workers toward the end of processing. Maybe batches of size `n`? I can get this implemented if we decide on a strategy, but will probably only bother doing it on the threads branch since that'll be merged into master and released once Julia 1.3 is released.

**Comment by tpoisot** [comment]
So we are running some omniscape analyses on our cluster, and the cost of the overehead is huge. Our parallel efficiency went from about 95% on a slower system where computing was the bottlenect, to under  40% when the bottleneck disappeared.

I'd be very happy to help in making this happen under 1.3, because right now we're squandering a lot of computing resources. I think that just sending batches of 10 solves would help a lot, and maps are typically large enough + the solves quick enough that idling workers at the end would be negligible.

**Comment by vlandau** [comment]
@tpoisot thanks for adding to this. I'll be much more focused on Omniscape development these next few weeks and this issue is high priority. I _might_ be able to get it done tomorrow, but otherwise, next week for sure. And agreed about idle workers, which is why I was thinking an argument for batch size with some default would be ideal.

**Comment by vlandau** [comment]
@tpoisot  You'll also see in [this commit](https://github.com/Circuitscape/Omniscape.jl/commit/c20a87d9a61d60fd47cad88879d150df41ed7ccf) on the threads branch that reducing the number of BLAS threads helped pretty significantly with this problem of reduced returns with added parallel workers. I reduced compute time by >20% in the example I was working with. Competition for parallel resources between Omniscape and BLAS was causing significant slowdown. Still, doing batches should help with the overhead issue, which I recognize is very different from the BLAS issue.

**Comment by vlandau** [comment]
Any input welcome, @tpoisot and @ranjanan 
Would it be efficient/ideal to simply add another for loop inside the threads for loop for solving batches of size `batch_size`?
e.g. switching this:
```julia
@threads for i in 1:n_targets
    solve_target!(i,
                  n_targets,
                  int_arguments,
                  targets,
                  sources_raw,
                  resistance_raw,
                  cs_cfg,
                  o,
                  calc_flow_potential,
                  correct_artifacts,
                  correction_array,
                  cum_currmap,
                  fp_cum_currmap)
end
```
To something like this:
```julia
@threads for i in 0:(n_batches - 1)
    start_ind = batch_size * i + 1
    end_ind = min(n_targets, start_ind + batch_size - 1) 
    
    for j in 1:n_batches
        solve_target!(j,
                      n_targets,
                      int_arguments,
                      targets,
                      sources_raw,
                      resistance_raw,
                      cs_cfg,
                      o,
                      calc_flow_potential,
                      correct_artifacts,
                      correction_array,
                      cum_currmap,
                      fp_cum_currmap)
    end
end
```

**Comment by vlandau** [comment]
Done at commit [8cb127e](https://github.com/Circuitscape/Omniscape.jl/commit/8cb127e6c8f03d6b51308083a37b6ad3489dd494) on the threads branch. A new argument, `parallel_batch_size`, can now be supplied to the .ini file. Specifies the batch size for sending out parallel jobs to threads. Defaults to 10. I noticed a pretty good reduction in overhead time.

Could be that we can reduce overhead even more, but closing this for now.

**Comment by tpoisot** [comment]
Perfect! As soon as 1.3.0 is released, we'll test on our cluster and report.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
