### ISSUE TITLE
Links to the doc are dead

### ISSUE THREAD

**Issue by tpoisot** [Circuitscape/Omniscape.jl#105]
Not sure where the doc lives now, but the links in the JOSS paper and from the badges don't work anymore

**Comment by vlandau** [comment]
Thanks for the heads up @tpoisot.

@ViralBShah @ranjanan looks like everything on docs.circuitscape.org  is down, including Circuitscape and my new package in progress SpatialGraphs.jl. I'm not sure what is going on. I can confirm SpatialGraphs docs were up this week. Circuitscape.org is still up though.

**Comment by vlandau** [comment]
In the mean time docs can be found here: https://circuitscape.github.io/Omniscape.jl/latest/

I think someone deleted the circuitscape.github.io repository, which was telling github to send docs to docs.circuitscape.org

**Comment by vlandau** [comment]
Thanks again @tpoisot. Someone did indeed delete the circuitscape.github.io repository. I recreated it and everything is back online.

**Comment by tpoisot** [comment]
:+1:

**Comment by ViralBShah** [comment]
It was me. I mistakenly thought it was an empty repo. Apologies.
