### ISSUE TITLE
Issues with runs in parallel

### ISSUE THREAD

**Issue by tpoisot** [Circuitscape/Omniscape.jl#11]
We're trying to run things on more than a single core, from an environment, and have been struggling so far. Here is the script, and we start julia with `julia --project` (but it doesn't matter):

~~~julia
@info "Activating the environment"
import Pkg; Pkg.activate(".")

@info "Loading Distributed"
using Distributed
addprocs(50; exeflags="--project")

@info "Importing environment on workers"
@everywhere begin
        import Pkg
        @info pwd()
        Pkg.activate(".")
        using Omniscape
end

@info "Run"
run_omniscape("test.ini")
~~~

Now, the error message we get is 

~~~
Starting up Omniscape to use 50 processes in parallel
ERROR: LoadError: On worker 2:
ArgumentError: Package Omniscape not found in current path:
- Run `import Pkg; Pkg.add("Omniscape")` to install the Omniscape package.
~~~

I'm guessing there is something we are missing -- the error message is the same in 1.0 to 1.3. Is there an obvious thing we are missing? The issue does not appear if we work from the default environment (but we would rather not install packages in it).

CC'ing @DominiqueCaron & @dlecourstessier

**Comment by vlandau** [comment]
@tpoisot Omniscape takes care of adding procs and distributing tasks for you. To enable parallel processing, you have to specify `parallelize=true` and `max_parallel=50` in your .ini file. Once you've done that, it's just `run_omniscape(<insert path to .ini>)`. Mind trying that and letting my know what happens?

**Comment by tpoisot** [comment]
sure, here is the whole session:

~~~
tpoisot@redacted:~/Varia/TestOmniscape$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.2) pkg> activate .
Activating environment at `~/Varia/TestOmniscape/Project.toml`

julia> using Omniscape
[ Info: Recompiling stale cache file /home/tpoisot/.julia/compiled/v1.2/Omniscape/uqaJf.ji for Omniscape [a38d70fc-99f5-11e9-1e3d-cbca093024c3]
run_omn	
julia> run_omniscape("test.ini")
Starting up Omniscape to use 30 processes in parallel
ERROR: On worker 2:
ArgumentError: Package Omniscape not found in current path:
- Run `import Pkg; Pkg.add("Omniscape")` to install the Omniscape package.
~~~

**Comment by tpoisot** [comment]
Note that even re-starting to avoid the pre-compilation step is not changing the output. Even starting julia with `julia --project` gives the same issue.

**Comment by vlandau** [comment]
Ohh, I see. Sorry, it must be something to do with `activate`, so Ixm not sure exactly what's going on. Have you considered using Docker so that you can avoid direct installation (then you wouldn't have to use activate)? I would even be happy to build a Docker image with the packages you need and pass it along to you.

**Comment by tpoisot** [comment]
In fact, looking at the code, `myaddprocs` is evaluating everything in `Main`?

https://github.com/Circuitscape/Omniscape.jl/blob/2ea129d17dfc9f070aa73552e40a64bd946622f9/src/utils.jl#L1-L4

Just to try, I installed Omniscape in the default environment, then activated the project, and it is now running in parallel very nicely.

**Comment by tpoisot** [comment]
From the top of my head, a fix could be

~~~ julia
function myaddprocs(n)
    addprocs(n; exeflags="--project")
    @everywhere import Omniscape
end
~~~

I haven't tried, but happy to submit a PR.

**Comment by vlandau** [comment]
I won't be able to get to it until Friday, but I can test that out. Once Julia 1.3 is released, Omniscape will actually be switching to multithreading instead of distributed for its parallel processing. I have a working branch of that version that you could use in Julia 1.3-rc4 if you want to try it out? The branch is called threads.

**Comment by tpoisot** [comment]
For now, I'm happy with installing Omniscape in the default environment, and waiting for multithreading. No sense in adding something when the next step is already in the works!

**Comment by vlandau** [comment]
Sounds good. Glad you got it working. Reach out also if you end up with some cool results you can share from your application of Omniscape!
