### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by RocioMartinez-Cillero** [Circuitscape/Omniscape.jl#116]
I've noticed a mistake in Omniscape documentation, section "Examples", where it says:
"Finally, map normalized current flow, which is calculated as flow potential divided by cumulative current."

Based on the paper and the results I'm getting from the algorithm, it should be "cumulative current/flow potential".

**Comment by ajzellmer** [comment]
Came here to say the same thing. Also related, in User Guide > Output Options there is an error here:

write_raw_currmap: One of true, false. Defaults to true. Save the raw cumulative current map to disk? Should always be set to true unless calc_flow_potential, calc_normalized_current, or both are true and you do not need the raw current output. If true, the cumulative current map is saved to disk as a raster called **"flowpotential"** with either a .tif or .asc extension (see `writeastifbelow) in theprojectname` directory.

Should be cum_currmap.tif instead

**Comment by vlandau** [comment]
Thank you @RocioMartinez-Cillero and @ajzellmer -- great catches! I'll work on a fix right now!
