### ISSUE TITLE
Data address invalid of the Example.

### ISSUE THREAD

**Issue by xiaoxiaomuse** [Circuitscape/Omniscape.jl#121]
In the example of " Forest connectivity in central Maryland",  the url ( "https://raw.githubusercontent.com/Circuitscape/datasets/main/") is  invalid, so we can not download the land cover tiff data.

**Comment by vlandau** [comment]
Thanks for posting an issue! It looks like GitHub has changed the formatting of their urls for raw content. Can you replace the URL in the code with "https://github.com/Circuitscape/datasets/blob/main/data/nlcd_2016_frederick_md.tif?raw=true" and let me know if that works for you? 

I'll update the URL in the docs later today when I have time but please also feel free to just do a PR if the URL above works for you.

**Comment by vlandau** [comment]
I just checked and the code as written does result in a valid url. Specifically the code generates this URL: raw.githubusercontent.com/Circuit scape/datasets/main/data/nlcd_2016_frederick_md.tif, which is then passed to `download` in the example. If you're just trying to navigate to url_base without adding the rest of the url (as is done in the subsequent line of code) then an invalid url error is expected.

**Comment by xiaoxiaomuse** [comment]
> Thanks for posting an issue! I'll look into this alte today. Can you replace the URL in the download code with "https://github.com/Circuitscape/datasets/blob/main/data/nlcd_2016_frederick_md.tif?raw=true" and let me know if that works for you?

Thank you very much.  This url can be well download.   en , the other one (raw.githubusercontent.com/Circuit scape/datasets/main/data/nlcd_2016_frederick_md.tif) still can not be found, maybe there is a problem in my internet.
