### ISSUE TITLE
Conditional connectivity options being ignored

### ISSUE THREAD

**Issue by thomarse-ef** [Circuitscape/Omniscape.jl#123]
I'm not sure if I've misunderstood how this works or if it's a bug but I can't seem to get conditional connectivity to work (or comparison with the future which is my goal). 

In my conditional file I've set two cells as 1, the rest as 0 (expecting 1s to only be connected with other 1s, 0s to only be connected with other 0s). When I run Omniscape with a radius that's smaller than the distance between the two 1 cells, I would expect that there would be nothing for either to connect to so the `cum_currmap` would be blank, however that's not what's happening. In fact, the result appears to be exactly the same whether `conditional` is set to `true` or `false`.

I've made a reproducible example (below), apologies it's in R - I'm not that familiar with Julia yet. 

Have I done something wrong, or is this a bug?

Example:
```
library(raster)

# source
sourcer <- raster(nrows=50, ncols=100)
sourcer <- setValues(sourcer, 0.0000000001)
sourcer[cellFromRowCol(sourcer, 25, 25)] <- 1000
sourcer[cellFromRowCol(sourcer, 25, 75)] <- 100
writeRaster(sourcer, "source.asc", overwrite = TRUE)

# resistance
resistr <- raster(sourcer)
resistr <- setValues(resistr, runif(length(resistr), max = 1, min = 0))
writeRaster(resistr, "resistance_map.asc", overwrite = TRUE)

# conditional 
condr <- raster(sourcer)
condr <- setValues(condr, 0)
condr[cellFromRowCol(condr, 25, 25)] <- 1
condr[cellFromRowCol(condr, 25, 75)] <- 1
writeRaster(condr, "conditional.asc", overwrite = TRUE)

## run omniscape here ##

# view result
result <- raster("omni/cum_currmap.tif")
plot(result)

```

This is my ini file:
```
[Required]
resistance_file = resistance_map.asc
source_file = source.asc
radius = 10
block_size = 1
project_name = omni

[General options]
source_from_resistance = false
calc_flow_potential = true
calc_normalized_current = true

solver = cholmod
resistance_is_conductance = true

parallelize = true
parallel_batch_size = 30

[Output options]
write_raw_currmap = true

[Conditional connectivity options]
conditional = true
n_conditions = 1
condition1_file = conditional.asc
comparison1 = exact

```

**Comment by Sumuses** [comment]
I also encountered this problem.  there is no difference between none condition and two conditions.

**Comment by vlandau** [comment]
Thanks for reporting this. Apologies for the delay in responding to this issue. Currently this project is maintained "pro bono" and in the developers' free time, so it might take me a week or two to look into this. If you don't hear back in a couple of weeks, please do post another comment to remind me. I'll post back here with an update when I have a chance to look at it.

**Comment by vlandau** [comment]
@Sumuses would you be able to share your INI and input files as well?

**Comment by Sumuses** [comment]
I am a new julia learner, so I put my code below, and put all test data are here:https://github.com/Sumuses/test-data-for-Omniscape
Thank you very much, Mr vlandau.

> # using package
using Omniscape, Rasters, Plots
#Reand and load data
land_cost, wkt, transform = Omniscape.read_raster("resistance.tif", Float64)      #resistance file
source, wkt, transform = Omniscape.read_raster("mamal.tif", Float64)                #source file
cpca1, wkt, transform = Omniscape.read_raster("cPCA1_c1.tif", Float64)            #condition 1 
fpca1, wkt, transform = Omniscape.read_raster("fPCA1_f1.tif", Float64)              #condition 2 
cpca2, wkt, transform = Omniscape.read_raster("cPCA2_c2.tif", Float64)            # future condition 1 
fpca2, wkt, transform = Omniscape.read_raster("fPCA2_f2.tif", Float64)               # future condition 1 

config = Dict{String, String}(
    "radius" => "50",      
    "block_size" => "3",
    "project_name" => "Output_con2",    #output Folders 
    "source_from_resistance" => "False",
    #"r_cutoff" => "100",                                      # Only forest pixels should be sources
    "source_file" => "mammal.tif",                       ##source file
    "buffer" => "50",  
    #"source_threshold" => "1", 
    "allow_different_projections"  => "True",
    "reclassify_resistance" => "False",  
    "calc_normalized_current" => "True",
    "calc_flow_potential" => "True",
    "conditional" => "True",    
    "n_conditions" => "2",        #two conditions
    "compare_to_future" => "Both",    
    "comparison1"  =>  "Within", 
    "condition1_lower"  => "-1",     
    "condition1_upper"  => "1",  
    "comparison2"  =>  "Within", 
    "condition2_lower"  => "-2.5",     
    "condition2_upper"  => "2.5" 
)

run_omniscape(
    config,
    land_cost, 
    source_strength = source,
    condition1 = cpca1,
    condition2 = cpca2,
    condition1_future = fpca1,
    condition2_future = fpca2,
    wkt = wkt,
    geotransform = transform,
    write_outputs = true
)

**Comment by vlandau** [comment]
@Sumuses so sorry this has slipped without any activity. Do things work as expected with one condition?

**Comment by vlandau** [comment]
@Sumuses your problem was because you had your comparison mode set to `"Within"` instead of `"within"`. It's case sensitive. I need to add a bunch of checks for options to make sure they're specified properly. I'll add this to the list. I'm going to close this issue.
