### ISSUE TITLE
enable BigTIFF support on write?

### ISSUE THREAD

**Issue by jessjaco** [Circuitscape/Omniscape.jl#130]
I think this is an easy fix to `options` in io.jl. I can send a PR.
![image](https://user-images.githubusercontent.com/1250693/233855411-c5908f88-90b5-4d12-9e94-560ff6c3421c.png)

Write options listed here: https://gdal.org/drivers/raster/gtiff.html. I only have experience with BIGTIFF=YES, but we could try the others ("IF_NEEDED", "IF_SAFER")

**Comment by vlandau** [comment]
Sorry for the late reply here. Happy to have you put in a PR if you'd like!

**Comment by vlandau** [comment]
Resolved by #136
