### ISSUE TITLE
UndefVarError 'read_raster' not defined

### ISSUE THREAD

**Issue by Zitronenschale** [Circuitscape/Omniscape.jl#133]
Good morning, 
I am trying to run the Omniscape example of this page: 

https://docs.circuitscape.org/Omniscape.jl/latest/examples/

unfortunately I always get this error when loading the raster file: 

julia> land_cover, wkt, transform = Omniscape.read_raster("C:/Users/keinp/nlcd_2016_frederick_md", Float64)
ERROR: UndefVarError: `read_raster` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ REPL[19]:1

The previous commands are executed. Can anyone help me?

Translated with www.DeepL.com/Translator (free version)

**Comment by digital-carver** [comment]
Based on [discussions on Zulip](https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/Omniscape.20Test), this is the result of version compatibility issues leading to Omniscape 0.4.0 being installed. Omniscape only allows version 0.8 of ArchGDAL, while Circuitscape wants the more recent version 0.10 of ArchGDAL. 

Would it be possible to bump up the compat bounds for ArchGDAL in Omniscape?

**Comment by vlandau** [comment]
Sure, I can update the compat for ArchGDAL and other packages. I'll work on getting this done soon, but feel free to ping me again if it's not done by the end of the day on Sunday. Thanks!

**Comment by digital-carver** [comment]
gentle ping @vlandau

**Comment by vlandau** [comment]
I just released a new version with updated compat entries. Please ensure you're using Julia 1.9 and try the examples again. If you end up running into the same error. Feel free to reopen this issue.
