### ISSUE TITLE
Fix documenter and tagbot

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Omniscape.jl#137]
TagBot and Documenter are both broken following upstream changes.

cc @ViralBShah @ranjanan just wanted to ping you here because it looks like you may have already resolved this (at least TagBot) for Circuitscape? Any tips?

**Comment by ViralBShah** [comment]
TagBot looks fine. The service has been a bit unreliable.

Documenter has released 1.0, so there are some breaking changes (that should be easy to fix). 
See https://github.com/JuliaDocs/Documenter.jl/blob/master/CHANGELOG.md

**Comment by vlandau** [comment]
Excellent, thanks so much @ViralBShah!

**Comment by ViralBShah** [comment]
Trying the bump in #141 to see if that helps fix the deployment issues, but may need some small updates.

**Comment by ViralBShah** [comment]
The failing doc push is probably related to tagbot not running reliably, and not due to Documenter. @ranjanan Any ideas how to fix it?
