### ISSUE TITLE
reclass_table should give a warning if reclassify_resistance is false

### ISSUE THREAD

**Issue by tpoisot** [Circuitscape/Omniscape.jl#145]
It's a little counterintuitive to pass a `reclass_table` and not have it applied because `reclassify_resistance` defaults to `false` - I know it's documented but I think it would make it safer for users to throw a warning or an info if the reclass table is *not* applied?

**Comment by vlandau** [comment]
Agreed @tpoisot this is on my list. Please feel free to open a PR as well, if you'd like!

**Comment by tpoisot** [comment]
I'm a little swamped this week, but I'll try to open a PR next week!
