### ISSUE TITLE
Julia/Omniscape not recognizing files [Solved: ini file mistake - no source specified]

### ISSUE THREAD

**Issue by beardant** [Circuitscape/Omniscape.jl#147]
I have tried with various computers, and in various folders, to run Omniscape but I keep getting the same error:
I'm using Julia 1.8.4.

Please find here the necessary files;

[omni_ex.zip](https://github.com/Circuitscape/Omniscape.jl/files/13851545/omni_ex.zip)

```
julia> using Omniscape
julia> run_omniscape("C:\\omni\\settingss.ini")

ERROR: the file "" does not exist
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] read_raster
   @ C:\Users\merijnb\.julia\packages\Omniscape\9gHf2\src\io.jl:14 [inlined]
 [3] run_omniscape(path::String)
   @ Omniscape C:\Users\merijnb\.julia\packages\Omniscape\9gHf2\src\main.jl:448
 [4] top-level scope
   @ REPL[6]:1
```

The 'settingss.ini' file has the following: 

```
[Required]
resistance_file = C:/omni/resras.tif
radius = 30
block_size = 3
project_name = C:/omni/omnibear

[General options]
source_from_resistance = false
r_cutoff = Inf
calc_normalized_current = true

parallelize = true
parallel_batch_size = 10

[Output options]
write_raw_currmap = true
write_as_tif = true
```

C:/omni/resras.tif is an existing file, while C:/omni/omnibear should be created automatically if I'm not mistaken.
I've also tried writing them with backslash (\) instead of slash (/) but that didn't make a difference.

Note that when I intentionally misspell the raster file in the settingss.ini, I get a different error:
`ERROR: the file "C:\Bears3\omni\resrasssss.tif" does not exist"`

**Comment by beardant** [comment]
With help of Vincent, the solution has been found.
My settings file did not specify a source file, but also did not specify
source_from_resistance = true

Therefore Julia did in fact find my resistance raster, but it kept looking for a source filet that was not there.

**Comment by vlandau** [comment]
Let's leave this open for now, as a reminder for me to get around to betting warning/error throws. I'll do this at the same time that I handle #145, and alternatively add some things to handle #146.
