### ISSUE TITLE
Error in fetch for summing current maps from workers

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Omniscape.jl#3]
@ranjanan, here's how to reproduce the error I'm getting with `@fetchfrom`
```julia
using Pkg; Pkg.add(PackageSpec("https://github.com/Circuitscape/Omniscape.jl", rev = "8cb24c1")
using Omniscape; Pkg.test("Omniscape")
```

**Comment by vlandau** [comment]
Appears to be fixed by wrapping the offending lines of code in a function, as per your suggestion, @ranjanan. Must have something to do with variable scopes.

**Comment by ranjanan** [comment]
Cool!

**Comment by vlandau** [comment]
@ranjanan Also, was able to replace that hacky `pmap` workaround for broadcsating variables by using `remotecall()` in a loop over the worker pool instead.
