### ISSUE TITLE
Suppress output from Circuitscape; but allow @info from Omniscape

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Omniscape.jl#41]
Output is too busy. Ideally we would just have two messages per solve (starting, and finished with time to complete). Right now there are up to 6 messages per solve and in parallel it is impossible to tell which "time to complete" message belongs to which Omniscape solve.

**Comment by vlandau** [comment]
@ranjanan is this possible?

**Comment by ViralBShah** [comment]
Yes, should be straightforward. I am sure it's a logging level thing. May be able to make it an optional argument to `compute` or something.

**Comment by vlandau** [comment]
Okay great! I can look into this next week on the Circuitscape side. It could be as easy as putting a Boolean in front of each `csinfo()`, e.g. `! suppress_info && csinfo(...)`

**Comment by ViralBShah** [comment]
I am pretty sure it is much less effort than that. The logging level setting can just be changed in one place, and all the Info messages can be done away with.

**Comment by vlandau** [comment]
> I am pretty sure it is much less effort than that. The logging level setting can just be changed in one place, and all the Info messages can be done away with.

Would that then suppress @info messages from Omniscape, too? I'll still need those.

**Comment by ViralBShah** [comment]
@ranjanan may need to answer that one. I am not familiar with the details - but it should be straightforward to figure it out.

**Comment by vlandau** [comment]
bumping for @ranjanan

**Comment by vlandau** [comment]
Currently a PR in the pipeline for Circuitscape, Circuitscape/Circuitscape.jl/pull/255, will just add an .ini arg to Omniscape that will be piped into Circuitscape once that PR is merged and next version of Circuitscape is released.
