### ISSUE TITLE
Test Omniscape with MKL solver in Circuitscape

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Omniscape.jl#44]
Mentioned in Circuitscape/Circuitscape.jl/issues/218. Would like to test in Omniscape using the MKL Circuitscape branch.

**Comment by vlandau** [comment]
@ViralBShah is this still worth doing, or did you say the PARDISO solver doesn't offer much savings over cg+amg?

**Comment by ViralBShah** [comment]
Relevant PR https://github.com/Circuitscape/Circuitscape.jl/pull/225

**Comment by vlandau** [comment]
Closing for now -- can re-open if/when Pardiso is implement in Circuitscape master
