### ISSUE TITLE
Add a walkthrough example to Omniscape docs

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Omniscape.jl#45]
Provide a section in the documentation with a worked example, describing rationale behind decision points surrounding model parameters, etc., to help provide guidance to users.

**Comment by ricschuster** [comment]
Hi @vlandau,

Great NACCB talk and great to see Omniscape development in Julia!
Do you happen to have a worked example that you could share at this point?
I'm new to Julia (R user), but am very curious to try this out and see if it could be useful for our work.

Thanks!

**Comment by vlandau** [comment]
Hi @ricschuster, super glad you enjoyed the talk, thanks for tuning in! I don't have a completely worked example yet, but I have some example .ini files that might helpful to check out for now? There are a bunch of test files (including .ini's, resistance surfaces, source strength surfaces, and climate rasters) [here](https://github.com/Circuitscape/Omniscape.jl/tree/main/test/input) that might be useful as a starting point?

**Comment by ricschuster** [comment]
Thanks @vlandau!
Do you by chance have a quick description of the files in the test folder, or should I just go about and play around with them?

**Comment by ricschuster** [comment]
Sorry, another question: do you happen to have some files for a 'realistic' example that you could share as well?
I do have resistance surfaces from circuitscape projects, but I want to make sure that the resistance and ini file combination works, before trying on our data.

**Comment by vlandau** [comment]
I don't have anything immediately on hand unfortunately, but I would like to add a "tutorial" folder to the repo with some small but non-random resistance surfaces in the coming weeks (maybe I can use the classic resistance surface that Brad created for Circuitscape.py). Any resistance surface that works for Circuitscape will also work for Omniscape, for what that's worth, but definitely a good call to start on a smaller problem to work out any kinks, etc.

I think [config3.ini](https://github.com/Circuitscape/Omniscape.jl/blob/main/test/input/config3.ini) would be a good place to start. It represents a simple use case, and you can cross reference with the [docs](https://circuitscape.github.io/Omniscape.jl/v0.3/) for descriptions of what each argument means.

To actually get it running on your machine, you could save config3.ini and resistance1.asc to your computer, let's say to a folder called omniscape-test, change input/resistance1.asc in the ini to resistance1.asc (since presumably you won't want to bother with also creating another folder at omniscape-test/input), then launch Julia.

In Julia, you'll want to change you're working directory to the omniscape-test folder because the paths are relative to the omniscape-test folder (just like in R, if you `setwd()`, you can just use file names in functions like `read_csv` instead of the full path). 

So
1. Open a julia terminal
2. run `cd("path/to/omniscape-test")` where that path will be identical to what you would put in `setwd` in R to change your working directory to omniscape-test
3. run `using Pkg; Pkg.add("Omniscape")` (only if Omniscape is not already installed)
4. using Omniscape
5. run_omniscape("config3.ini")

This will run the problem, and outputs will be written to a folder inside omniscape-test called test3, as specified in the .ini foler. Once this is working, you can play around with changing things in the .ini like the `resistance_file`  (e.g. you could change it to the path of one of your resistance surfaces) and you'd probably also want to change `radius`.

Okay, tons of info there and almost certainly not perfectly clear, so please let me know if I can clarify anything!

**Comment by ricschuster** [comment]
Thanks very much for this description!

I'm happy to report that this is working without any hiccups and I do get the outputs in folder test3. 
Really looking forward to exploring this further and scaling up.

**Comment by vlandau** [comment]
Awesome! Don't hesitate to reach out with any more questions, bug reports, or feature requests as well!

**Comment by vlandau** [comment]
Closed with addition of new Examples section in the docs :tada:

**Comment by ikwabia** [comment]
I would like to provide the path to my tif file which is on my local machine, how do I do it.
