### ISSUE TITLE
Error: Error building `GDAL`:

### ISSUE THREAD

**Issue by joncjones** [Circuitscape/Omniscape.jl#47]
Just as a heads up for Windows users, a simple problem and a simple fix:

When first running Pkg.add("Omniscape") I was getting the following error:
...
>Building GDAL → `C:\Users\jonat\.julia\packages\GDAL\cvf6T\deps\build.log`
┌ Error: Error building `GDAL`:
>ERROR: LoadError: LoadError: Your platform ("x86_64-w64-mingw32", parsed as "x86_64-w64-mingw32-gcc8-cxx11") is not supported by this package!

As a result Pkg.test("Omniscape") also failed with the recommendation to:
>ERROR: LoadError: GDAL not installed properly, run Pkg.build("GDAL"), restart Julia and try again

This recommendation did not fix the issue but shutting down Julia, restarting Julia and manually adding GDAL has resolved the issue:
>Pkg.add("GDAL")

Note I did restart Julia on the second occasion using 'Run as administrator'.
Not sure if that made the difference.
Now running the test package completes ok.
I have a full error log if needs.
 
For ref - my desktop system: 
Windows 10/64GB RAM/Intel i7-8700k/NVIDIA GeForce GTX 1080 Ti

**Comment by vlandau** [comment]
Thanks for posting this here! This will definitely be useful if any other users encounter a similar problem. Glad you figured it out.

**Comment by vlandau** [comment]
could be related: yeesian/ArchGDAL.jl/pull/125
