### ISSUE TITLE
Setting parallel threads on Windows x64 PC

### ISSUE THREAD

**Issue by ekbuchholtz** [Circuitscape/Omniscape.jl#52]
I was wondering if setting the number of threads in the terminal is still the way to get Omniscape (v0.3.0) to work in parallel? I am using a Windows x64 PC with Julia v1.4.2. Everything works great, but Omniscape is only using one worker. Using Circuitscape (v5.6.0) in Julia on the same machine does work in parallel. 

Prior to opening Julia, the code I used in the command line terminal:
set JULIA_NUM_THREADS=4

Thanks

**Comment by vlandau** [comment]
Hi Erin, are you launching Julia from the same command prompt in which you set the `JULIA_NUM_THREADS` variable? I think in Windows `set JULIA_NUM_THREADS=4` only sets it for the current session, so you need to launch Julia from that same session.

**Comment by ekbuchholtz** [comment]
Hi - thanks, that was the issue. Launching Julia from the same session works.
