### ISSUE TITLE
Add error throws when required arguments are missing from the .ini

### ISSUE THREAD

**Issue by ranjanan** [Circuitscape/Omniscape.jl#8]
Good thing to tell users whenever they haven't specified enough information to make a minimal omniscape problem.

**Comment by vlandau** [comment]
This initial comment is addressed in the docs currently, where there is a [section](https://circuitscape.github.io/Omniscape.jl/v0.2/usage/#Required-arguments-1) under usage detailing the required arguments to the .ini, but currently there are not any error throws if args are missing.
