### ISSUE TITLE
Problem running Omniscape

### ISSUE THREAD

**Issue by HGSvR** [Circuitscape/Omniscape.jl#91]
julia> using Pkg; Pkg.add("Omniscape")
   Updating registry at `C:\Users\ac102092\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
No Changes to `C:\Users\ac102092\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\ac102092\.julia\environments\v1.5\Manifest.toml`

julia> run_omniscape
ERROR: UndefVarError: run_omniscape not defined

Do you have any suggestions? I was running "using Pkg; ..." before, guess was successful.
Thanks
Hans

**Comment by vlandau** [comment]
You need to run `using Omniscape` to load the package into the environment. Then the run_omnicape function will be available.
