### ISSUE TITLE
Pkg.add error

### ISSUE THREAD

**Issue by peggyn7** [Circuitscape/Omniscape.jl#97]
When trying to load either Omniscape or Circuitscape in Julia, I get the following error:
UndefVarError:Pkg not defined.

So, these packages are no longer loading automatically with the Julia installation. What is the best way to load Omniscape or Circuitscape so that you can add it in Julia with no issues?

**Comment by peggyn7** [comment]
I figured it out.  Instructions

Toggle to the Pkg REPL:
At the Julia> prompt, type "]" and hit Enter

Add the Omniscape package:
At the pkg> prompt type "add Omniscape"

Toggle back to the Julia REPL:
Click on "Backspace" to return to Julia> prompt

Import the Omniscape package:
At the Julia> prompt, type "import Omniscape"

But how to run it?

**Comment by vlandau** [comment]
To run this in a script you have to do `using Pkg` or `using Omniscape` to load the package and its functions into the environment. Hope that helps!

**Comment by trantom** [comment]
Hi Vincent.  Thank you for the help.  Peggy and I worked together to get it to run thanks to all the available documentation and discussions on gitter.  Feel free to close this issue!

**Comment by vlandau** [comment]
Excellent! So glad that the documentation helped! Always feel free to post back here or on Gitter if any more questions come up!

**Comment by Penelopi** [comment]
Hello, what if I am running Julia through Conda using the bash language. These instructions did not work for this case.
